### ISSUE TITLE
Add SSR support

### ISSUE THREAD

**Issue by euvl** [euvl/vue-notification#26]
Per #11, need to make sure plugin does work with SSR.

**Comment by francescobm** [comment]
very nice plugin! a pity it doesn't work with SSR, any plans to release this enhancement ?

**Comment by euvl** [comment]
yeah, but i dont have enough time for it right now 😭

**Comment by CJRoman** [comment]
It worked for me to add `target: node` to webpack config. I created PR https://github.com/euvl/vue-notification/pull/48

**Comment by MartinBucko** [comment]
Same here. Impossible to use with Nuxt.js and SSR..

```
Exception has occurred: ReferenceError
ReferenceError: document is not defined
    at addStyle (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/~/vue-style-loader/lib/addStylesClient.js:116:1)
    at addStylesToDom (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/~/vue-style-loader/lib/addStylesClient.js:100:1)
    at module.exports (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/~/vue-style-loader/lib/addStylesClient.js:54:1)
    at Object.hasDocument (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/src/Notifications.vue?5994:8:1)
    at __webpack_require__ (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/webpack/bootstrap 41ba13c4827cd5d12480:19:1)
    at Object.defineProperty.value (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/src/Notifications.vue:3:1)
    at __webpack_require__ (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/webpack/bootstrap 41ba13c4827cd5d12480:19:1)
    at Object._typeof (/home/martinez/www/myproject/node_modules/vue-notification/dist/index.js:528:77)
    at __webpack_require__ (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/webpack/bootstrap 41ba13c4827cd5d12480:19:1)
    at module.exports.rawScriptExports (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/webpack/bootstrap 41ba13c4827cd5d12480:65:1)
    at /home/martinez/www/myproject/node_modules/vue-notification/dist/index.js:79:10
    at webpackUniversalModuleDefinition (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/webpack/universalModuleDefinition:3:1)
    at Object.<anonymous> (/home/martinez/www/myproject/node_modules/vue-notification/dist/webpack:/webpack/universalModuleDefinition:10:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

**Comment by pedramk** [comment]
@euvl Oh man! Come on we're waiting for SSR.

**Comment by euvl** [comment]
SSR support added,  /dist/ssr.js

**Comment by francescobm** [comment]
Niiiiiiice!! Thanks man

**Comment by starikov-kirill** [comment]
@euvl Hello, how I can use velocity animation, if I include ssr version? It's doesn't work for me.

**Comment by smitpatelx** [comment]
> SSR support added, /dist/ssr.js

Hey, I think you forgot to add this to your readme. At first I uninstalled this plugin.
